// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrQ-of4LTZ_Q1xMleDiO33yAOr4sDnstA',
    appId: '1:537669815185:web:71bd77764174b5743ce830',
    messagingSenderId: '537669815185',
    projectId: 'clinic-9c9c4',
    authDomain: 'clinic-9c9c4.firebaseapp.com',
    storageBucket: 'clinic-9c9c4.appspot.com',
    measurementId: 'G-LN02FEG3SF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1OjSGrpGD6qtNmaipZltkZmWI6n4-qgc',
    appId: '1:537669815185:android:e1c0683d4192b0663ce830',
    messagingSenderId: '537669815185',
    projectId: 'clinic-9c9c4',
    storageBucket: 'clinic-9c9c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT1A2FS0_-NY8WzY0eR8c9ZNIr6F13WJE',
    appId: '1:537669815185:ios:b0bbcc7fbddeed313ce830',
    messagingSenderId: '537669815185',
    projectId: 'clinic-9c9c4',
    storageBucket: 'clinic-9c9c4.appspot.com',
    iosBundleId: 'com.example.doctorappointment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT1A2FS0_-NY8WzY0eR8c9ZNIr6F13WJE',
    appId: '1:537669815185:ios:f56ab30d3dea79803ce830',
    messagingSenderId: '537669815185',
    projectId: 'clinic-9c9c4',
    storageBucket: 'clinic-9c9c4.appspot.com',
    iosBundleId: 'com.example.doctorappointment.RunnerTests',
  );
}
